name: build

on:
  push:
    branches:
      - branch1

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/devendrabetaque/react-app:${{ github.sha }} .
          docker login docker.io -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push docker.io/devendrabetaque/react-app:${{ github.sha }}

      # - name: Configure Docker for GHCR
      #   run: |
      #     echo "{\"auths\":{\"ghcr.io\":{\"username\":\"$GITHUB_ACTOR\",\"password\":\"${{ secrets.GHCR_PAT }}\"}}}" > $HOME/.docker/config.json

      # - name: Push to GitHub Container Registry
      #   run: |
      #     docker tag docker.io/devendrabetaque/react-app:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/react-app:${{ github.sha }}
      #     docker push ghcr.io/${{ github.repository_owner }}/react-app:${{ github.sha }}

